### ISSUE TITLE
Auto-wiring dependencies for setter injection

### ISSUE THREAD

**Issue by J7mbo** [rdlowrey/auryn#1]
As the title explains, would it be possible to include this capability in here, so that when Auryn performs it's reflection to read constructor signatures, could the reflection also be performed for methods within the class?

Obviously this would increase overheard significantly, but if everything's cached - that shouldn't be an issue. I'm going to take a look at the source over the course of this week but, what are your opinions on this @rdlowrey?

**Comment by vlakarados** [comment]
Just stumbled upon this problem here:

Beforehand I had an instance of a controller a

    $controller = $injector->make($runner[0]);

and called it like

    $result = call_user_func_array(array($controller, $runner[1]), $execution[2]);

That worked great (I could pass any number of any params as `$execution[2]`).

Now I tried to make that possible using `->execute()`, but that requires passing all the arguments manually filling the array.

So how may I pass all arguments plus injecting the ones typehinted?

I think that way controller method would look like this:

    public function dosomething($urlSegment1, $urlSegment2, \App\Repository\Users $users)
    {
    }

That looks possible only with the 'raw named parameter', but not unnamed. Forcing all controller actions to use named params like $arg1, $arg2 etc. is definitely not worth it.

I hope you understand my issue, maybe it's a poor design, but I don't think this is the case

**Comment by J7mbo** [comment]
Are the `$id` and `$name` parameters parameters passed in from your GET / POST request (as in [slugs](http://symfony.com/doc/current/book/routing.html#routing-in-action))?

**Comment by vlakarados** [comment]
Exactly, so they're not constant, there may be one, more or none

**Comment by vlakarados** [comment]
I see that I may do that like (IIRC) it was in codeigniter using something like `->segment(n)`, but that's ugly :)

**Comment by J7mbo** [comment]
Get your `$params` as an array from your request, then prefix them with a `:` for scalar injection with Auryn:

        array_walk($params, function($value, $key) use (&$args) {
            $args[sprintf(':%s', $key)] = $value;
        });

This is how it works for my in Symfony, but you can customise for yourself. See how I'm making the controller, then executing the action with the given `$args` (the : params).

        /** Executed by the HTTP Kernel **/
        return function () use ($controller, $action, $args) {
            return $this->injector->execute([$this->injector->make($controller), $action], $args);
        };

**Comment by vlakarados** [comment]
@J7mbo, thank you, works great, the only downside is that I should name the arguments the same way as they're named in the `$args`, which comes from nikic/FastRoute, but that makes the code even cleaner by forcing to stick to same names!
