### ISSUE TITLE
class_alias and preparers

### ISSUE THREAD

**Issue by mattsah** [rdlowrey/auryn#171]
From what I can see if a class or interface is aliased preparer for a class doesn't work.  I would expect the following to have a bar value of `b`:

```
>>> class Foo { public $bar = 'a'; }
>>> class_alias('Foo', 'Bar');
=> true
>>> $broker->prepare('Foo', function($instance) { $instance->bar = 'b'; });
=> Auryn\Injector {#9}
>>> $bar = $broker->make('Bar');
=> Foo {#234
     +bar: "a",
   }
```

**Comment by kelunik** [comment]
This would need special support. Is there any way to query the defined aliases?

**Comment by mattsah** [comment]
Reflection is likely the only way I'd think, but I don't think that would be too terrible.  This also seems to affect `delegate()` calls.  But if the reflections are cached, presumably on a delegate or even a prepare one may need to be doing reflection at some point anyway.

**Comment by Danack** [comment]
> I can see if a class or interface is aliased preparer for a class doesn't work.

That's working as intended. The set of instructions for prepares and delegates only work against the class they were instructed to work against, rather than trying to guess what they should do.

If you really need to use class aliases then you should duplicate the delegate/prepare instructions you pass to Auryn for those classes.
