### ISSUE TITLE
Question: Property visibility 

### ISSUE THREAD

**Issue by epiphany** [rdlowrey/auryn#180]
Just curious if you would consider making the Injectors properties protected vs their current private visibility?

**Comment by Danack** [comment]
I wouldn't have a problem with that.

We do suggest that if people want custom behaviour added to the injector to extend the class to implement it, and changing private -> protected would allow that to be a bit more powerful.

Anyone have an objection?

**Comment by kelunik** [comment]
I'd rather not do that. This is a nightmare to keep backwards compatible then. What's your use case?

**Comment by epiphany** [comment]
Suppose someone is interested in determining whether or not an abstraction is aliased, has a definition, or otherwise within a child class. 

As of right now the injector is limited to the package updates and lacks any ability for extension.

Amazing package yes, but limited to the functionality of those who contribute.

**Comment by Danack** [comment]
> This is a nightmare to keep backwards compatible then.

Anyone who is directly extending a class from another library, should only do so if they're willing to pay the price when that library changes at whatever version.

Seeing as it looks like being about four years since there has been an internal change that would break any extending class, it doesn't sound like a huge concern.

**Comment by kelunik** [comment]
> Anyone who is directly extending a class from another library, should only do so if they're willing to pay the price when that library changes at whatever version.

I do not agree with that statement. Extension should be prevented where possible, unless its explicitly designed as an extension point.

The information requested can already be accessed via the `inspect` method. I'm fine with adding more inspection methods that expose the internal configuration, but I don't think changing the visibility of the properties directly is the way to go.

> Seeing as it looks like being about four years since there has been an internal change that would break any extending class, it doesn't sound like a huge concern.

Because nobody added additional features that required any breakages. And nobody cared to refactor anything.

I'm probably soon™ going to refactor some things, because I want to introduce `make` specific definitions that are type based instead of based on the parameter names. Just not sure when I'll find time for that.

**Comment by kelunik** [comment]
Closing, as `inspect` can be used. PRs welcome to expose information via dedicated methods.
