### ISSUE TITLE
Injector::prepare exception

### ISSUE THREAD

**Issue by Furgas** [rdlowrey/auryn#195]
Shouldn't `Injector::prepare` throw `ConfigException` instead of `InjectionException`?

**Comment by kelunik** [comment]
What makes you think so?

**Comment by Danack** [comment]
Probably because it happens during configuring the injector, not when the injector is making something.

I'm guessing some idiot used InjectionException::fromInvalidCallable because it was there, when they probably should have moved that static method to InjectorException so it can be used as ConfigException::fromInvalidCallable  ?

**Comment by Danack** [comment]
Should be fixed in a9a6146b876fa7f626e8ca41a360e044017b299b


Injector::prepare now throws ConfigException instead of InjectionException
