### ISSUE TITLE
Simplifying raw parameter injection

### ISSUE THREAD

**Issue by rdlowrey** [rdlowrey/auryn#66]
This is something I've been meaning to do for awhile ...

Currently you're required to to use the raw injection prefix when defining parameters for any argument type even if it's not a string.

``` php
<?php
class MyClass {
    function __construct(StdClass $obj){}
}
$injector->define('MyClass', [':obj' => new StdClass]);
```

However, the `:` prefix should only be necessary if the passed argument is a string (so the injector can differentiate between a class name and an actual raw argument). The injector should be smart enough to know that if a non-string array value was passed in the class's injection definition that it's meant to be a raw parameter. This is a small change that would eliminate one of the major sources of confusion for new users.

**Comment by vlakarados** [comment]
Wouldn't it be better if strings would not require that prefix, but class names would start from backslash? Fully qualified class names passed like strings like '\Auryn\Provider' would be resolved, while 'Auryn\Provider' would be interpreted as a string?

**Comment by mattsah** [comment]
@vlakarados what if you need to pass a string that starts with '\' for some reason?  What if, in fact, you're passing a class name as a string?  It's useful to have a way to ensure that it can be specified by the dev, and not leave everything up to Auryn to guess.

**Comment by ascii-soup** [comment]
I'm worried this might be more confusing, since this would make raw string arguments a special case.
It's a pretty big departure from how things work at the moment, but for the sake of consistency, would it better to require the colon prefix only if you are passing in a class name? That way, everything is a raw parameter unless you provide the colon prefix, which denotes that this is a "special" parameter (i.e. you are telling Auryn to run the given class name through the dependency-resolver)?

Big BC-break, but given that it's pre-1.0, is it worth doing? Have I misunderstood something?

**Comment by garrettw** [comment]
I know I'm stirring the pot a little, and this is a bit of a tangent, but I gotta know: do people really like to (or find it easy or logical to) specify parameters by name rather than by order?

Now I'm not educated on how many of the popular DICs work, but I personally find it more intuitive to go by param order because that's the way I'd be doing things if I wasn't using a DIC. I don't want to worry about what variable names some class uses internally, nor do I understand why someone would want to.

I also realize that the ability to assign by name allows you to do things like assign a consistent value to any class using the same variable name, but – and maybe this is my inexperience speaking, but – I don't really see the use case for that. Is there one?

**Comment by staabm** [comment]
> I also realize that the ability to assign by name allows you to do things like assign a consistent value to any class using the same variable name, but – and maybe this is my inexperience speaking, but – I don't really see the use case for that. Is there one?

IMO the benefit in named parameters is a more readable client code

**Comment by garrettw** [comment]
I dunno, just seems like it would require having to consult the API docs more than you might otherwise.

**Comment by mattsah** [comment]
@garrettw the benefit of having named parameters for injection is that you can specify only a single parameter... I suppose you could do this using explicit integer keys:

```
[0 => 'Whatever']
```

I do agree with concerns about fragility, but I suspect it's not much more likely to change than the order of parameters, and being able to specify a single dependency more clearly (particulary in the case of any number of optional dependencies) is nice.

**Comment by ascii-soup** [comment]
> more readable client code

and

> you can specify only a single parameter

seem to be the two best reasons I can think of in general.

One of my current use cases is using the execute() method on controller methods and auto-wiring the URL parameters in named routes to method arguments in the controller. As long as we use the same name for the parameter in the route and the method signature, it will get passed in automatically (and all object dependencies are resolved too). This removes a lot of annoying boilerplate and is made trivial thanks to Auryn's use of named arguments.

**Comment by garrettw** [comment]
@mattsah or, potentially, implicit integer keys as well.

**Comment by kelunik** [comment]
I don't see any benefit in that smartness, especially if all it simplifies is saving one character.
