### ISSUE TITLE
Implementing container-interop interface

### ISSUE THREAD

**Issue by raulferras** [rdlowrey/Auryn#77]
I'm using Auryn together with XStatic as a way to get something similar to Laravel Facades.
The problem is XStatic requires an instance of a Service Container that implements this [Container Interface](https://github.com/container-interop/container-interop) already being used by other **Dependency Injector Containers**.

It only requires implementing these two methods in the *Provider* (which you already has, but with other names).

```
public function get($id)
{
    return $this->make($id);
}

public function has($id)
{
    return $this->isDefined($id);
}
```

I'm currently extending Auryn\Provider so it is not much of a hassle, just wondering if it is wort the consideration.

**Comment by J7mbo** [comment]
Why on earth would you want to go near Laravel’s “Facades”?

Apart from that bombshell, you can use the adapter pattern to ‘forward’ calls from your required interface to auryn’s interface? That may help :-) Google ‘adapter pattern’ if you haven’t used it before. Also, Auryn is an Injector not a container.

**Comment by raulferras** [comment]
Well I'm just experimenting and wanted to replicate it. 
The adapter pattern would suffice thanks.

**Comment by J7mbo** [comment]
Np. Just so you know, passing your container anywhere (apart from your bootstrap or a factory) is likely utilising it as a service locator - which is an anti-pattern. Is there another way you can use Auryn without turning it into one?

**Comment by raulferras** [comment]
As I said I'm experimenting with this Dependency Injection thing.  
The main issue I'm facing is how to handle the different dependencies controller's actions may need. Laravel uses Facades, but as you said this is just a form of Service Locator, so I'm struggling how I can avoid using Service Locators and/or defining a gigantic list of dependencies in the controller constructor.

**Comment by J7mbo** [comment]
Awesome, that's a great way forward. As soon as you have Auryn running `make()` on your controllers and running `execute()` on your controller method, you can typehint for what you want in any controller and it's 'plug and play' for all your libraries. Everything from there forward is then DI-based.

You might want to look at where your controllers are actually executed with Laravel and extend that class, make Laravel use your extended version, and do the above logic. This will involve prefixing any get parameters with `:` so that you can scalar typehints (as in Symfony `slugs`) and have those params passed in.

As for a gigantic list of dependencies, each controller method will have its own requirements right. So your `execute()` call takes care of that. I put common dependencies in a base class for my controller (like session, entity manager, logged in user etc), extend that, and have method-specific injection for each controller method.

**Comment by raulferras** [comment]
You mean as in the "App-Bootstrapping" example in documentation right?  
However, I worry about a scenary where a heavy dependency (in terms of time of instantation/memory footprint for example) that would be only used by a method would be instantiated every time the controller is created... but I guess I could create another controller with only that method to leverage other `actions`...

**Comment by J7mbo** [comment]
Usually it's best to use method-specific stuff when not every method will be using the object.

Auryn allows you to use factories for lazy instantiation, so you're creating a (not yet resolved) closure which does the lifting only when you try and use it. That may be beneficial in those heavy lifting cases where you still want constructor injection.

**Comment by raulferras** [comment]
I don't quite understand how a factory method can help me in that scenario. Could you give me an example?

On the other hand, I've re-read the documentation and saw the `execute` method you were referring above, wouldn't that allow me to specify per method dependencies better?

**Comment by J7mbo** [comment]
Yep, `make` your controller then `execute` on the controller method. [This](https://github.com/J7mbo/silex-auth-skeleton/blob/master/src/App/AurynControllerResolver.php) may be useful, it's how I do it in Silex.

If there's something I need in a constructor but may only use it in one or two methods out of say 8, then I create a factory (not with Auryn, just an actual factory) and DI that instead. The factory's create method returns the newly created object but only when I call it. Factories are also useful for delaying the instantiation of an object so you can provide it runtime gathered data (ie data provided from a user's request).

**Comment by shadowhand** [comment]
I'd like to request that this issue be reopened, as container-interop is a beneficial to the ecosystem as a whole by allowing us to pick and choose components.

**Comment by J7mbo** [comment]
But Auryn isn't a container, it's an *injector* - I would argue a container is an anti-pattern - you're painstakingly storing everything in a magic box which you pull out when you like (i.e. service locator). Why would Auryn support such a massive waste of time and effort?

**Comment by rdlowrey** [comment]
I don't personally have much interest in integrating interop capability into the library directly (as I philosophically disagree with its existence). But it should be fairly straightforward for someone to create a simple wrapper if they're so inclined.

**Comment by shadowhand** [comment]
@J7mbo because as the issue author said:

> It only requires implementing these two methods in the Provider (which you already has, but with other names).

Your implementation of dependency injection doesn't have to change at all, it simply gives users more options to choose from. Similar to how we have `psr-3` for standard logging, we can use `container-interop` as a universal interface for DI.

> as I philosophically disagree with its existence

That's a fine opinion to have, but your willfully making it more difficult for your users to do what they want.

**Comment by shadowhand** [comment]
Not to mention that it's just another way to promote your opinion about how people should be doing DI. I fail to see any downsides.

**Comment by J7mbo** [comment]
Oh no, it's the PSR recruitment brigade! Quick, hide! ;D

It's not my implementation or opinion of Dependency Injection: Dependency Injection and Service Locator are *patterns*, one of them is an anti-pattern, and they usually oppose each other.

You can always write an adapter to deal with your required interface. For the record, I hugely disagree with "container-interop" - just because frameworks decide they're going to use it doesn't mean it's right - I'm not talking from a PHP only perspective here either.

**Comment by shadowhand** [comment]
Your attitude is very rude. Good luck with your project.

**Comment by J7mbo** [comment]
So is yours saying it's just me promoting my opinion... good luck to you too.

**Comment by shadowhand** [comment]
I'm not sure what is rude about suggesting that you provide **more options** for users, allowing your package to be used by a larger number of users. Chive on.

**Comment by J7mbo** [comment]
That's a little like saying it's a good thing that Laravel allows you to access everything statically.

**Comment by shadowhand** [comment]
It's absolutely not the same thing at all.

**Comment by J7mbo** [comment]
Would you like help writing an adapter? Perhaps we could work together on that and host it on github to make it work for others.. I don't mind... I just *really* don't agree that more options is always better.

**Comment by shadowhand** [comment]
Again, there's no reason for a separate adapter or a separate package. The entirety of what you would have to do is require `container-interop/container-interop` and implement the two interface methods as aliases to existing methods. I don't really have any interest in working with you on any project, given the attitude you've expressed.

Having more options **isn't** necessarily better, except when it makes your software better, which is clearly the case here.

**Comment by J7mbo** [comment]
But we've already established that it (1) puts forward poor practice (so, it doesn't make your software better, it merely makes it easier to write given your current architecture) and (2) the package owner doesn't want to do it. If they're not good enough reasons not to, I don't know what is.

If you think that that would make your software better, then I don't want to work with you either. Your suggestion would only make the library more complaint with a joke interface. That's all.

**Comment by bwoebi** [comment]
Usually you have interop interfaces for sharing injecting implementations somewhere with a common API… But the point of a Dependency injector is to inject dependencies and to be injected itself.

There's no real reason to inject this and so no reason to have it implementing a common interface. But feel free to create a tiny `class WorseAuryn extends Auryn\Provider implements Interop\Container\Container-Interface { /* the two methods */ }`.
Also I think reducing dependencies as far as possible is a good thing (not talking about duplicating code, but about not really necessary deps). There's no reason for Auryn\Provider to implement that interface. It doesn't add any value to it.

**Comment by shadowhand** [comment]
Not to resurrect a ghost, but I just wanted to mention that I now completely agree with @rdlowrey and @J7mbo on this subject... the container-interop is a huge mistake and totally unnecessary. We use Auryn with @sparkphp and love it!

**Comment by J7mbo** [comment]
Just out of interest @shadowhand, what changed your mind? Was there something in particular with the interface? I'm wondering if there's any knowledge you could share on that one :-)

**Comment by shadowhand** [comment]
@J7mbo Nothing specifically with the interface. What changed was the realization that Auryn could exist purely in the very outer layers of my application and be completely isolated from nearly everything. Nothing in the "business logic" of my application would need to know about it.

That said, I think there is potentially a tiny bit of convenience in having a common interface that allows people to replace the injector that is used by a framework, *even though the framework does not **need** to depend on a specific injector*, because pushing all injector configuration onto the user is not convenient for anyone.
